const countryMap = {
  AC: "Pulau Ascension",
  AD: "Andora",
  AE: "Uni Emirat Arab",
  AG: "Antigua & Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarktika",
  AR: "Argentina",
  AS: "Samoa Amerika",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Kepulauan Aland",
  AZ: "Azerbaijan",
  BA: "Bosnia-Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgia",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "St. Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Karibia Belanda",
  BR: "Brasil",
  BS: "Bahama",
  BT: "Bhutan",
  BV: "Pulau Bouvet",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Kanada",
  CC: "Kepulauan Cocos (Keeling)",
  CD: "Kongo (Republik Demokratik)",
  CF: "Republik Afrika Tengah",
  CG: "Kongo (Republik)",
  CH: "Swiss",
  CI: "Cote d'Ivoire",
  CK: "Kepulauan Cook",
  CL: "Cile",
  CM: "Kamerun",
  CO: "Kolombia",
  CR: "Kosta Rika",
  CV: "Tanjung Verde",
  CW: "Curaçao",
  CX: "Pulau Natal",
  CY: "Siprus",
  CZ: "Republik Cheska",
  DE: "Jerman",
  DJ: "Jibuti",
  DK: "Denmark",
  DM: "Dominika",
  DO: "Republik Dominika",
  DZ: "Aljazair",
  EC: "Ekuador",
  EE: "Estonia",
  EG: "Mesir",
  EH: "Sahara Barat",
  ER: "Eritrea",
  ES: "Spanyol",
  ET: "Etiopia",
  FI: "Finlandia",
  FJ: "Fiji",
  FK: "Kepulauan Falkland",
  FM: "Mikronesia",
  FO: "Kepulauan Faeroe",
  FR: "Prancis",
  GA: "Gabon",
  GB: "Inggris Raya",
  GD: "Grenada",
  GE: "Georgia",
  GF: "Guyana Prancis",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Guinea Ekuatorial",
  GR: "Yunani",
  GS: "Georgia Selatan & Kep. Sandwich Selatan",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Pulau Heard & Kep. McDonald",
  HN: "Honduras",
  HR: "Kroasia",
  HT: "Haiti",
  HU: "Hungaria",
  ID: "Indonesia",
  IE: "Irlandia",
  IL: "Israel",
  IM: "Pulau Man",
  IN: "India",
  IO: "Teritorial Britania di Samudra Hindia",
  IQ: "Irak",
  IS: "Islandia",
  IT: "Italia",
  JE: "Jersey",
  JM: "Jamaika",
  JO: "Yordania",
  JP: "Jepang",
  KE: "Kenya",
  KG: "Kirgizstan",
  KH: "Kamboja",
  KI: "Kiribati",
  KM: "Komoro",
  KN: "St. Kitts & Nevis",
  KR: "Korea Selatan",
  KW: "Kuwait",
  KY: "Kepulauan Cayman",
  KZ: "Kazakstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "St. Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lituania",
  LU: "Luksemburg",
  LV: "Latvia",
  LY: "Libia",
  MA: "Maroko",
  MC: "Monako",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "St. Martin",
  MG: "Madagaskar",
  MH: "Kepulauan Marshall",
  MK: "Makedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Makau",
  MP: "Kep. Mariana Utara",
  MQ: "Martinik",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maladewa",
  MW: "Malawi",
  MX: "Meksiko",
  MY: "Malaysia",
  MZ: "Mozambik",
  NA: "Namibia",
  NC: "Kaledonia Baru",
  NE: "Niger",
  NF: "Pulau Norfolk",
  NG: "Nigeria",
  NI: "Nikaragua",
  NL: "Belanda",
  NO: "Norwegia",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "Selandia Baru",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "Polinesia Prancis",
  PG: "Papua Nugini",
  PH: "Filipina",
  PK: "Pakistan",
  PL: "Polandia",
  PM: "St. Pierre & Miquelon",
  PN: "Kepulauan Pitcairn",
  PR: "Puerto Riko",
  PS: "Palestina",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Rumania",
  RS: "Serbia",
  RU: "Rusia",
  RW: "Rwanda",
  SA: "Arab Saudi",
  SB: "Kepulauan Solomon",
  SC: "Seychelles",
  SE: "Swedia",
  SG: "Singapura",
  SH: "St. Helena",
  SI: "Slovenia",
  SJ: "Svalbard & Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "Sudan Selatan",
  ST: "São Tomé & Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SZ: "Swaziland",
  TA: "Tristan da Cunha",
  TC: "Kep. Turks & Caicos",
  TD: "Cad",
  TF: "Teritorial Prancis Selatan",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor Leste",
  TM: "Turkimenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turki",
  TT: "Trinidad & Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraina",
  UG: "Uganda",
  UM: "Kep. Terluar AS",
  US: "Amerika Serikat",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Kota Vatikan",
  VC: "St. Vincent & Grenadines",
  VE: "Venezuela",
  VG: "Kep. Virgin Inggris",
  VI: "Kep. Virgin AS",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis & Futuna",
  WS: "Samoa",
  XK: "Kosovo",
  YE: "Yaman",
  YT: "Mayotte",
  ZA: "Afrika Selatan",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export default countryMap;
