const uptMap = {
  1000: "Kantor Pusat",
  1001: "Balai Besar Uji Standar Karantina Hewan, Ikan, dan Tumbuhan",
  1002: "Balai Uji Terap Teknik dan Metode Karantina Hewan, Ikan, dan Tumbuhan",
  1100: "Balai Karantina Hewan, Ikan, dan Tumbuhan Aceh",
  1101: "Bandara Sultan Iskandar Muda",
  1102: "Pelabuhan Laut Sabang",
  1103: "Pelabuhan Laut Lhokseumawe",
  1104: "Pelabuhan Laut Meulaboh",
  1105: "Pelabuhan Laut Sinabang",
  1106: "Pelabuhan Laut Kuala Langsa",
  1107: "Pelabuhan Laut Simeuleu",
  1200: "Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Sumatera Utara",
  1201: "Bandara Kualanamu",
  1202: "Bandara Sisingamangaraja",
  1203: "Pelabuhan Belawan",
  1204: "Pelabuhan Tanjung Balai Asahan",
  1205: "Pelabuhan Laut Sibolga",
  1300: "Balai Karantina Hewan, Ikan, dan Tumbuhan Sumatera Barat",
  1301: "Bandara Minangkabau",
  1302: "Pelabuhan Laut Mentawai",
  1400: "Balai Karantina Hewan, Ikan, dan Tumbuhan Riau",
  1401: "Bandara Sultan Syarif Kasim II",
  1402: "Pelabuhan Laut Dumai",
  1403: "Pelabuhan Laut Bengkalis",
  1404: "Pelabuhan Laut Tembilahan",
  1405: "Pelabuhan Laut Selat Panjang",
  1406: "Pelabuhan Laut Sungai Guntung",
  1407: "Pelabuhan Laut Tanjung Buton",
  1500: "Balai Karantina Hewan, Ikan, dan Tumbuhan Jambi",
  1501: "Bandara Sultan Thaha",
  1502: "Pelabuhan Laut Kuala Tungkal",
  1600: "Balai Karantina Hewan, Ikan, dan Tumbuhan Sumatera Selatan",
  1601: "Bandara Sultan Mahmud Badaruddin II Palembang",
  1602: "Pelabuhan Tanjung Api-api",
  1700: "Balai Karantina Hewan, Ikan, dan Tumbuhan Bengkulu",
  1701: "Bandara Fatmawati",
  1800: "Balai Karantina Hewan, Ikan, dan Tumbuhan Lampung",
  1801: "Bandara Raden Inten II",
  1802: "Pelabuhan Penyeberangan Bakauheni",
  1900: "Balai Karantina Hewan, Ikan, dan Tumbuhan Kepulauan Bangka Belitung",
  1901: "Bandara H.A.S. Hanandjoeddin",
  1902: "Bandara Depati Amir",
  1903: "Pelabuhan Muntok",
  1904: "Pelabuhan Laut Pangkal Balam",
  2100: "Balai Karantina Hewan, Ikan, dan Tumbuhan Kepulauan Riau",
  2101: "Bandara Hang Nadim",
  2102: "Bandara Raja Haji Fisabilillah",
  2103: "Pelabuhan Laut Telaga Punggur",
  2104: "Pelabuhan Tanjung Uban",
  2105: "Pelabuhan Laut Kijang",
  2106: "Pelabuhan Tanjung Balai Karimun",
  2107: "Pelabuhan Tanjung Batu",
  2108: "Pelabuhan Laut Moro",
  2109: "Pelabuhan Laut Natuna",
  3100: "Balai Besar Karantina Hewan, Ikan, dan Tumbuhan DKI Jakarta",
  3101: "Pelabuhan Laut Tanjung Priok",
  3102: "Pelabuhan Sunda Kelapa",
  3103: "Bandara Halim Perdana Kusuma",
  3200: "Balai Karantina Hewan, Ikan, dan Tumbuhan Jawa Barat",
  3201: "Bandara Kertajati",
  3202: "Pelabuhan Laut Cirebon",
  3300: "Balai Karantina Hewan, Ikan, dan Tumbuhan Jawa Tengah",
  3301: "Bandara Adi Sumarmo",
  3302: "Bandara Ahmad Yani",
  3303: "Pelabuhan Laut Tanjung Intan",
  3304: "Pelabuhan Laut Tegal",
  3400: "Balai Karantina Hewan, Ikan, dan Tumbuhan Daerah Istimewa Yogyakarta",
  3401: "Bandara Yogyakarta International Airport (YIA)",
  3402: "Bandara Adi Sucipto",
  3500: "Balai Karantina Hewan, Ikan, dan Tumbuhan Jawa Timur",
  3501: "Bandara Juanda",
  3502: "Pelabuhan Penyeberangan Ketapang",
  3503: "Bandara Abdul Rahman Saleh",
  3504: "Pelabuhan Laut Tanjung Perak",
  3505: "Pelabuhan Pulau Kangean",
  3506: "Bangkalan",
  3600: "Balai Karantina Hewan, Ikan, dan Tumbuhan Banten",
  3601: "Bandara Soekarno Hatta",
  3602: "Pelabuhan Penyeberangan Merak",
  5100: "Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Bali",
  5101: "Bandara I Gusti Ngurah Rai",
  5102: "Pelabuhan Laut Celukan Bawang",
  5103: "Pelabuhan Penyeberangan Padang Bai",
  5104: "Pelabuhan Penyeberangan Gilimanuk",
  5200: "Balai Karantina Hewan, Ikan, dan Tumbuhan Nusa Tenggara Barat",
  5201: "Bandara Internasional Lombok",
  5202: "Pelabuhan Laut Lembar",
  5203: "Pelabuhan Laut Bima",
  5204: "Pelabuhan Penyeberangan Sape",
  5205: "Pelabuhan Laut Badas",
  5206: "Pelabuhan Laut Kayangan",
  5207: "Pelabuhan Laut Poto Tano",
  5300: "Balai Karantina Hewan, Ikan, dan Tumbuhan Nusa Tenggara Timur",
  5301: "Bandara El Tari",
  5302: "Pelabuhan Laut Ende",
  5303: "Pelabuhan Laut Reo",
  5304: "Pelabuhan Laut Waingapu",
  5305: "Pelabuhan Laut Sabu",
  5306: "Pelabuhan Laut Rote",
  5307: "Pelabuhan Laut Atapupu",
  5308: "Pelabuhan Laut Alor",
  5309: "Pelabuhan Laut Waikelo",
  5310: "Pelabuhan Laut Labuan Bajo",
  5311: "Pelabuhan Laut Maumere",
  5312: "PLBN Wini",
  5313: "PLBN Motaain",
  5314: "PLBN Motamasin",
  6100: "Balai Karantina Hewan, Ikan, dan Tumbuhan Kalimantan Barat",
  6101: "Bandara Supadio",
  6102: "Bandara Rahadi Usman",
  6103: "PLBN Entikong",
  6104: "PLBN Aruk",
  6105: "PLBN Nanga Badau",
  6106: "PLBN Jagoi Babang",
  6200: "Balai Karantina Hewan, Ikan, dan Tumbuhan Kalimantan Tengah",
  6201: "Bandara Tjilik Riwut",
  6202: "Pelabuhan Laut Pangkalan Bun",
  6203: "Pelabuhan Laut Sampit",
  6300: "Balai Karantina Hewan, Ikan, dan Tumbuhan Kalimantan Selatan",
  6301: "Bandara Syamsudin Noor",
  6302: "Pelabuhan Laut Batu Licin",
  6303: "Pelabuhan Laut Kotabaru",
  6400: "Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Kalimantan Timur",
  6401: "Bandara Sultan Aji Muhammad Sulaiman",
  6402: "Pelabuhan Sungai Samarinda",
  6403: "Pelabuhan Laut Kariangau",
  6404: "Pelabuhan Laut Semayang",
  6405: "Pelabuhan Laut Lok Tuan Bontang",
  6406: "Bandara APT Pranoto",
  6407: "Pelabuhan Laut Berau",
  6500: "Balai Karantina Hewan, Ikan, dan Tumbuhan Kalimantan Utara",
  6501: "Bandara Juwata Tarakan",
  6502: "Pelabuhan Laut Tanjung Selor",
  6503: "PLBN Sebatik",
  6504: "PLBN Nunukan",
  7100: "Balai Karantina Hewan, Ikan, dan Tumbuhan Sulawesi Utara",
  7101: "Bandara Sam Ratulangi",
  7102: "Pelabuhan Laut Bitung",
  7103: "Pelabuhan Laut Tahuna",
  7200: "Balai Karantina Hewan, Ikan, dan Tumbuhan Sulawesi Tengah",
  7201: "Bandara Mutiara Sis Al-Jufri",
  7202: "Pelabuhan Pantoloan",
  7203: "Pelabuhan Laut Luwuk Banggai",
  7204: "Pelabuhan Laut Toli-toli",
  7300: "Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Sulawesi Selatan",
  7301: "Bandara Sultan Hasanudin",
  7302: "Pelabuhan Laut Pare-Pare",
  7303: "Pelabuhan Laut Jeneponto",
  7304: "Pelabuhan Laut Bajoe",
  7400: "Balai Karantina Hewan, Ikan, dan Tumbuhan Sulawesi Tenggara",
  7401: "Bandara Halu Oleo",
  7402: "Bandara Betoambari",
  7403: "Pelabuhan Laut Kendari",
  7404: "Pelabuhan Laut Kolaka",
  7405: "Pelabuhan Laut Raha Muna",
  7406: "Pelabuhan Laut Wanci Wakatobi",
  7500: "Balai Karantina Hewan, Ikan, dan Tumbuhan Gorontalo",
  7501: "Bandara Jalaluddin",
  7600: "Balai Karantina Hewan, Ikan, dan Tumbuhan Sulawesi Barat",
  7601: "Bandara Tampa Padang",
  7602: "Pelabuhan Laut Pasang Kayu",
  7603: "Pelabuhan Laut Majene",
  8100: "Balai Karantina Hewan, Ikan, dan Tumbuhan Maluku",
  8101: "Bandara Pattimura",
  8102: "Pelabuhan Laut Tual",
  8103: "Pelabuhan Laut Kobisadar",
  8104: "Pelabuhan Laut Namlea",
  8105: "Pelabuhan Laut Dobo",
  8200: "Balai Karantina Hewan, Ikan, dan Tumbuhan Maluku Utara",
  8201: "Bandara Sultan Babullah",
  8202: "Pelabuhan Laut Tobelo",
  8203: "Pelabuhan Laut Bacan",
  8204: "Pelabuhan Laut Sanana",
  8205: "Pelabuhan Laut Morotai",
  9100: "Balai Besar Karantina Hewan, Ikan, dan Tumbuhan Papua",
  9101: "Bandara Sentani",
  9102: "Pelabuhan Laut Jayapura",
  9103: "Pelabuhan Laut Biak",
  9104: "PLBN Skouw",
  9105: "Pelabuhan Laut Serui",
  9200: "Balai Karantina Hewan, Ikan, dan Tumbuhan Papua Barat",
  9201: "Pelabuhan Laut Bintuni",
  9202: "Pelabuhan Laut Wasior",
  9203: "Pelabuhan Laut Kaimana",
  9204: "Pelabuhan Laut Fakfak",
  9300: "Balai Karantina Hewan, Ikan, dan Tumbuhan Papua Selatan",
  9301: "Bandara Mopah",
  9302: "Pelabuhan Sungai Bade",
  9303: "PLBN Sota",
  9304: "PLBN Yetetkun Boven Digoel",
  9400: "Balai Karantina Hewan, Ikan, dan Tumbuhan Papua Tengah",
  9401: "Pelabuhan Laut Nabire",
  9500: "Balai Karantina Hewan, Ikan, dan Tumbuhan Papua Pegunungan",
  9600: "Balai Karantina Hewan, Ikan, dan Tumbuhan Papua Barat Daya",
  9601: "Satpel Uji Coba",
};

export default uptMap;
